package store

import (
	"context"
	"strings"

	"github.com/google/uuid"

	"github.com/kaziwise/kaziwise_backend/internal/domain"
)

const certCols = `
	ct.id, ct.org_id, ct.learner_id, ct.course_id, ct.campaign_id, ct.attempt_id,
	ct.certificate_number, ct.verification_code, ct.learner_name, ct.course_title,
	ct.score, ct.completed_at, ct.issued_at, ct.revoked_at, ct.revoked_reason`

func scanCertificate(row interface{ Scan(...any) error }) (*domain.Certificate, error) {
	var c domain.Certificate
	err := row.Scan(&c.ID, &c.OrgID, &c.LearnerID, &c.CourseID, &c.CampaignID, &c.AttemptID,
		&c.CertificateNumber, &c.VerificationCode, &c.LearnerName, &c.CourseTitle,
		&c.Score, &c.CompletedAt, &c.IssuedAt, &c.RevokedAt, &c.RevokedReason)
	if err != nil {
		return nil, mapErr(err)
	}
	c.Valid = c.RevokedAt == nil
	return &c, nil
}

// scanCertificateWithOrg consumes the extra organisations.name column that
// the org-scoped and public lookups select.
func scanCertificateWithOrg(row interface{ Scan(...any) error }) (*domain.Certificate, error) {
	var c domain.Certificate
	err := row.Scan(&c.ID, &c.OrgID, &c.LearnerID, &c.CourseID, &c.CampaignID, &c.AttemptID,
		&c.CertificateNumber, &c.VerificationCode, &c.LearnerName, &c.CourseTitle,
		&c.Score, &c.CompletedAt, &c.IssuedAt, &c.RevokedAt, &c.RevokedReason, &c.OrgName)
	if err != nil {
		return nil, mapErr(err)
	}
	c.Valid = c.RevokedAt == nil
	return &c, nil
}

type IssueCertificateParams struct {
	OrgID            uuid.UUID
	LearnerID        uuid.UUID
	CourseID         uuid.UUID
	CampaignID       *uuid.UUID
	AttemptID        *uuid.UUID
	Score            float64
	CompletedAt      string
	LearnerName      string
	CourseTitle      string
	VerificationCode string
}

// IssueCertificate writes a certificate. The certificate number is
// generated by a database sequence and the verification code is generated
// by the caller; both are protected by unique constraints, so a collision
// fails loudly instead of silently overwriting an existing record.
func (db *DB) IssueCertificate(ctx context.Context, p IssueCertificateParams) (*domain.Certificate, error) {
	var c domain.Certificate
	err := db.pool.QueryRow(ctx, `
		insert into certificates (org_id, learner_id, course_id, campaign_id, attempt_id,
		                          certificate_number, verification_code, learner_name,
		                          course_title, score, completed_at)
		values ($1,$2,$3,$4,$5,
		        'KZW-' || to_char(now(), 'YYYY') || '-' ||
		          lpad(nextval('cert_number_seq')::text, 6, '0'),
		        $6, $7, $8, $9, $10::timestamptz)
		returning `+certCols,
		p.OrgID, p.LearnerID, p.CourseID, p.CampaignID, p.AttemptID,
		p.VerificationCode, p.LearnerName, p.CourseTitle, p.Score, p.CompletedAt).
		Scan(&c.ID, &c.OrgID, &c.LearnerID, &c.CourseID, &c.CampaignID, &c.AttemptID,
			&c.CertificateNumber, &c.VerificationCode, &c.LearnerName, &c.CourseTitle,
			&c.Score, &c.CompletedAt, &c.IssuedAt, &c.RevokedAt, &c.RevokedReason)
	if err != nil {
		return nil, mapErr(err)
	}
	c.Valid = true
	return &c, nil
}

func (db *DB) CertificateByID(ctx context.Context, orgID, id uuid.UUID) (*domain.Certificate, error) {
	c, err := scanCertificateWithOrg(db.pool.QueryRow(ctx,
		`select `+certCols+`, o.name from certificates ct
		 join organisations o on o.id = ct.org_id
		 where ct.org_id = $1 and ct.id = $2`, orgID, id))
	if err != nil {
		return nil, err
	}
	return c, nil
}

// CertificateByCode is the public verification lookup. It is deliberately
// not org-scoped: a verification code is the only credential needed to
// prove a certificate is genuine, and a stranger must be able to check it.
func (db *DB) CertificateByCode(ctx context.Context, code string) (*domain.Certificate, error) {
	c, err := scanCertificateWithOrg(db.pool.QueryRow(ctx, `
		select `+certCols+`, o.name
		from certificates ct join organisations o on o.id = ct.org_id
		where lower(ct.verification_code) = lower($1)
		   or lower(ct.certificate_number) = lower($1)`, strings.TrimSpace(code)))
	if err != nil {
		return nil, err
	}
	return c, nil
}

func (db *DB) ListCertificates(ctx context.Context, orgID uuid.UUID, learnerID *uuid.UUID, page, perPage int) ([]domain.Certificate, int, error) {
	b := orgScope(orgID)
	if learnerID != nil {
		b.add("ct.learner_id = $" + itoa(len(b.values())+1))
		b.args = append(b.args, *learnerID)
	}
	base := `select ` + certCols + `, o.name from certificates ct
		join organisations o on o.id = ct.org_id` + b.whereClause() +
		` order by ct.issued_at desc`
	countSQL := `select count(*) from certificates ct` + b.whereClause()

	rows, total, err := db.paginate(ctx, db.pool, base, countSQL, b.values(), perPage, (page-1)*perPage)
	if err != nil {
		return nil, 0, err
	}
	defer rows.Close()
	out := []domain.Certificate{}
	for rows.Next() {
		c, err := scanCertificateWithOrg(rows)
		if err != nil {
			return nil, 0, err
		}
		out = append(out, *c)
	}
	return out, total, mapErr(rows.Err())
}

// CertificateForAttempt returns the certificate already issued for a
// passing attempt, so a retake or a repeated submit never issues a second
// certificate for the same pass.
func (db *DB) CertificateForAttempt(ctx context.Context, attemptID uuid.UUID) (*domain.Certificate, error) {
	return scanCertificate(db.pool.QueryRow(ctx,
		`select `+certCols+` from certificates ct where ct.attempt_id = $1`, attemptID))
}

// CertificateForLearnerCourse returns an existing valid certificate for a
// learner on a course, used as a fallback when a re-attempt passes again.
func (db *DB) CertificateForLearnerCourse(ctx context.Context, learnerID, courseID uuid.UUID) (*domain.Certificate, error) {
	return scanCertificate(db.pool.QueryRow(ctx,
		`select `+certCols+` from certificates ct
		 where ct.learner_id = $1 and ct.course_id = $2 and ct.revoked_at is null
		 order by ct.issued_at desc limit 1`, learnerID, courseID))
}

func (db *DB) RevokeCertificate(ctx context.Context, orgID, id uuid.UUID, reason string) (*domain.Certificate, error) {
	tag, err := db.pool.Exec(ctx, `
		update certificates set revoked_at = now(), revoked_reason = $1
		where org_id = $2 and id = $3 and revoked_at is null`, reason, orgID, id)
	if err != nil {
		return nil, mapErr(err)
	}
	if tag.RowsAffected() == 0 {
		return nil, ErrNotFound
	}
	return db.CertificateByID(ctx, orgID, id)
}
